### ISSUE TITLE
This might be a bit dumb, but how are you guys getting ip addresses?

### ISSUE THREAD

**Issue by syllogismos** [edsu/anon#105]
I'm trying to do this with Govt Of India, but I don't know how to get the ip addresses. Little bit of googling didn't help.

**Comment by lgommans** [comment]
Here is some information about it: http://security.stackexchange.com/questions/113044/how-to-identify-a-companys-public-network-address-range

In summary, there are no simple methods that reliably give you a result for any given organization. There are various tools you can use, but often you need a starting point like one of their IP addresses.

(I just noticed this is an old issue, but I hope it will still be helpful to new readers.)
