### ISSUE TITLE
Enhancment: @metadata in ranges.json

### ISSUE THREAD

**Issue by lokal-profil** [edsu/anon#115]
For a completely externalised ranges.json file it might be nice to add an "@metadata" object containing information such as source of ranges, last date they were verified etc.

I'm currently unsure how adding a field like this would be handled by the app since I can't figure out how it deals with incorrectly formatted range objects. If it does throw a wrench in the works would it be possible to make it skip name=@metadata (or some similar convention)?

**Comment by edsu** [comment]
I'm sorry I just haven't needed this functionality.
