### ISSUE TITLE
Anon project access for @AussieParlEdits

### ISSUE THREAD

**Issue by ineffyble** [edsu/anon#142]
Hey,

I'd like to request access to the project for migrating @AussieParlEdits across, so that it's more stable in future.

Tool Labs username is **effyelden**

**Comment by ineffyble** [comment]
Am I able to bump this?

**Comment by edsu** [comment]
Sorry for the delay! I don't see effyelden on Tools Labs, but I do see ineffyble. Is that you?

**Comment by ineffyble** [comment]
Oops, yes, I think I may have changed username since opening this request.

**Comment by edsu** [comment]
Ok, I've added you to the project. See if you are able to ssh in and `become anon`. Once you do that you should be able to see a README file that has some instructions in it. Let me know if you run into any trouble! I'll leave this ticket open until we get it working.

**Comment by ineffyble** [comment]
I believe I have successfully added the bot details to `config.json`, confirmed the bot was working, committed the changes, stopped the previous version with `jstop` and started it again.

**Comment by edsu** [comment]
@ineffyble it looks like there's a missing IP address in the `Department of Health` which is preventing the anon from running (the anon.err file is full of errors). Can you fix that part of your config or remove it and restart it?

Thanks for committing your changes to Git btw!

**Comment by edsu** [comment]
Actually, I'm going to remove the stanza myself and restart in case you aren't watching this issue closely. Please feel free to add it back in when you figure out what the second IP in the pair should be.

**Comment by ineffyble** [comment]
Hey, I just added second IP now - it was a single address, not sure how I missed it.

**Comment by edsu** [comment]
Oh, I see you have done it already?
