### ISSUE TITLE
EventStreams?

### ISSUE THREAD

**Issue by steko** [edsu/anon#144]
The new official [EventStreams service](https://wikitech.wikimedia.org/wiki/EventStreams) seems interesting. I have no idea about the benefits it could bring to anon but perhaps the pros and cons of IRC based wikichanges vs EventStreams could be discussed here?

That being said I thin anon is working ok, and Wikipedia has so much infrastructure built up around the IRC stream that they aren't going to be turning it off anytime soon. So a general discussion of the pros/cons of EventStreams vis-a-vis IRC probably belongs in some Wikipedia space.

**Comment by edsu** [comment]
I think one of the benefits is that it should be easier to connect via HTTP than the IRC protocol. It would be useful to run a stability test to see how it fares for weeks at a time. Another benefit is that HTTP (port 80/443) is less likely to be blocked on a network than IRC (port 6667).

**Comment by lokal-profil** [comment]
I just got a warning that the RC stream is being shut down in about 1.5 months.

**Comment by edsu** [comment]
Ok, thanks.

**Comment by ottomata** [comment]
It is true!  But RCStream != IRC RecentChanges.  IRC RecentChanges (which it seems anon runs on?) will be around for a while.

**Comment by ottomata** [comment]
But, yeah, switch to EventStreams!

**Comment by lokal-profil** [comment]
Ah. my apologies for panicking =)

**Comment by edsu** [comment]
Everything is still working for now, so I'm closing this.
