### ISSUE TITLE
Anon project access for @1600PennEdits

### ISSUE THREAD

**Issue by ezramechaber** [edsu/anon#148]
Hi, is it possible to gain access to the Anon instance through Tool Labs?

The account will run here: https://twitter.com/1600PennEdits. I'm @ezram on WikiTech.

Thanks!

**Comment by edsu** [comment]
Hi @ezramechaber!  I'm already running [whitehousedits](https://twitter.com/whitehousedits) with a fair number of followers on wikimedia labs with a set of IP ranges that were [derived](https://github.com/govtrack/govtrack.us-web/blob/master/website/middleware.py#L25-L28) from govtrack. It has been very quiet so far, so if you have any insight into missing or changed IP ranges please let me know. Also I'd be happy to add you as an admin on the Wikimedia Labs project if you would like to help maintain the bot.

**Comment by ezramechaber** [comment]
@edsu Ah, that's great! I hadn't seen that account on the list, so I wasn't clear on who was maintaining that one. I suspect the IP ranges changed at some point last year, and haven't seen a better list unfortunately.
