### ISSUE TITLE
Follow a Wikipedia category

### ISSUE THREAD

**Issue by jarib** [edsu/anon#63]
This probably requires calling out to the Wikimedia API (at least it doesn't seem to appear in IRC), but it would be cool to be able to follow all edits of articles in a given category, e.g. http://en.wikipedia.org/wiki/Category:Current_events.

**Comment by marrakchino** [comment]
Hi @jarib , did you manage to find a way to perform this ?

Thanks!

**Comment by jarib** [comment]
Never did explore it further, no.
